import { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    careerRoadmaps: 'Career Roadmaps',
    search: 'Search',
    myCourses: 'My Courses',
    gamification: 'Gamification',
    profile: 'Profile',
    certificates: 'Certificates',
    leaderboard: 'Leaderboard',
    adminPanel: 'Admin Panel',
    analytics: 'Analytics',
    superAdmin: 'Super Admin',
    logout: 'Logout',
    liveClasses: 'Live Classes',
    assignments: 'Assignments',
    peerReview: 'Peer Review',

    // Common
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    back: 'Back',
    noData: 'No data available',
    points: 'Points',
    badges: 'Badges',
    shop: 'Shop',
    challenges: 'Challenges',
    rewards: 'Rewards',

    // Dashboard
    welcomeBack: 'Welcome back',
    continueLearning: 'Continue your learning journey',
    continueWatching: 'Continue Watching',
    learningGoals: 'Learning Goals',
    noGoals: 'No goals set. Add a daily or weekly learning goal!',
    quickStats: 'Quick Stats',
    learningFields: 'Learning Fields',
    noFields: 'No fields available yet',
    activeCourse: 'Active Course',
    noActiveCourse: 'No Active Course',
    noActiveCourseDesc: 'Browse fields below and enroll in a course to start learning',
    courseCompleted: 'Course Completed!',
    viewCertificate: 'View Certificate',
    todaysChallenges: "Today's Challenges",
    viewAll: 'View All',
    aiRecommendations: 'AI Recommendations',
    noRecommendations: 'Complete some courses to get personalized recommendations!',

    // Course
    lectures: 'lectures',
    completed: 'Completed',
    inProgress: 'In Progress',
    notStarted: 'Not Started',
    allLecturesDone: 'All lectures completed! Take the quiz to get your certificate!',
    markComplete: 'Mark as Complete',
    yourNotes: 'Your Notes',
    saved: 'Saved',
    selectLecture: 'Select a lecture to start watching',
    speed: 'Speed',
    noVideo: 'No YouTube video available',
    addVideoUrl: 'Please add a YouTube URL in admin panel',
    courseLocked: 'Course Locked',
    completeCurrentFirst: 'Pehle apna current course complete karein.',
    goToMyCourses: 'Go to My Courses',

    // Gamification
    earnBadges: 'Earn badges, collect points, complete challenges, and unlock rewards!',
    yourBadges: 'Your Badges',
    noBadges: 'No badges yet. Start learning to earn badges!',
    pointsShop: 'Points Shop',
    pointsAvailable: 'points available',
    noShopItems: 'No items in the shop yet.',
    todayChallenges: "Today's Challenges",
    allChallengesDone: 'All challenges completed today! Come back tomorrow for more.',
    noChallenges: 'No challenges for today. Check back tomorrow!',
    earned: 'Earned!',
    owned: 'Owned',
    buy: 'Buy',
    needMore: 'Need more',
    claim: 'Claim',
    claimed: 'Claimed',
    locked: 'Locked',

    // Live Classes
    upcomingClasses: 'Upcoming Live Classes',
    noUpcomingClasses: 'No upcoming live classes',
    joinClass: 'Join Class',
    classDetails: 'Class Details',
    instructor: 'Instructor',
    platform: 'Platform',
    startTime: 'Start Time',
    endTime: 'End Time',
    liveNow: 'Live Now',
    scheduled: 'Scheduled',
    ended: 'Ended',

    // Assignments
    trackAssignments: 'Assignments',
    noAssignments: 'No assignments for this track',
    submitAssignment: 'Submit Assignment',
    alreadySubmitted: 'Already Submitted',
    uploadFile: 'Upload File',
    textContent: 'Text Content',
    submit: 'Submit',
    grade: 'Grade',
    feedback: 'Feedback',
    dueDate: 'Due Date',
    totalPoints: 'Total Points',
    assignmentSubmitted: 'Assignment submitted successfully!',

    // Peer Review
    pendingReviews: 'Pending Reviews',
    noPendingReviews: 'No pending reviews',
    clarity: 'Clarity',
    completeness: 'Completeness',
    creativity: 'Creativity',
    comments: 'Comments',
    submitReview: 'Submit Review',
    reviewSubmitted: 'Review submitted successfully!',
    myReviews: 'My Reviews',
    reviewsReceived: 'Reviews Received',

    // Profile
    overview: 'Overview',
    password: 'Password',
    security: 'Security',
    activity: 'Activity',
    emailVerification: 'Email Verification',
    verified: 'Verified',
    notVerified: 'Not Verified',
    resendEmail: 'Resend Email',
    twoFactor: 'Two-Factor Authentication',
    sessionManagement: 'Session Management',
    logoutAllDevices: 'Logout All Devices',
    pushNotifications: 'Push Notifications',

    // Language
    language: 'Language',
    english: 'English',
    urdu: 'Urdu',

    // Appearance
    appearance: 'Appearance',
    theme: 'Theme',
    accentColor: 'Accent Color',
    fontSize: 'Font Size',
    blue: 'Blue',
    green: 'Green',
    purple: 'Purple',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
  },
  ur: {
    dashboard: 'ڈیش بورڈ',
    careerRoadmaps: 'کیریئر روڈ میپ',
    search: 'تلاش',
    myCourses: 'میرے کورسز',
    gamification: 'گیمفیکیشن',
    profile: 'پروفائل',
    certificates: 'سرٹیفیکیٹ',
    leaderboard: 'لیڈر بورڈ',
    adminPanel: 'ایڈمن پینل',
    analytics: 'تجزیہ',
    superAdmin: 'سپر ایڈمن',
    logout: 'لاگ آؤٹ',
    liveClasses: 'لائیو کلاسز',
    assignments: 'اسائنمنٹس',
    peerReview: 'پیر ریویو',

    loading: 'لوڈ ہو رہا ہے...',
    save: 'محفوظ کریں',
    cancel: 'منسوخ کریں',
    delete: 'حذف کریں',
    edit: 'ترمیم',
    add: 'شامل کریں',
    back: 'واپس',
    noData: 'کوئی ڈیٹا نہیں',
    points: 'پوائنٹس',
    badges: 'بیجز',
    shop: 'دکان',
    challenges: 'چیلنجز',
    rewards: 'انعامات',

    welcomeBack: 'خوش آمدید',
    continueLearning: 'اپنا سیکھنے کا سفر جاری رکھیں',
    continueWatching: 'دیکھتے رہیں',
    learningGoals: 'سیکھنے کے اہداف',
    noGoals: 'کوئی ہدف مقرر نہیں۔ روزانہ یا ہفتہ وار ہدف شامل کریں!',
    quickStats: 'فوری اعدادوشمار',
    learningFields: 'سیکھنے کے شعبے',
    noFields: 'ابھی تک کوئی شعبہ دستیاب نہیں',
    activeCourse: 'فعال کورس',
    noActiveCourse: 'کوئی فعال کورس نہیں',
    noActiveCourseDesc: 'نیچے شعبوں کو براؤز کریں اور سیکھنا شروع کرنے کے لیے کورس میں داخلہ لیں',
    courseCompleted: 'کورس مکمل!',
    viewCertificate: 'سرٹیفیکیٹ دیکھیں',
    todaysChallenges: 'آج کے چیلنجز',
    viewAll: 'سب دیکھیں',
    aiRecommendations: 'AI سفارشات',
    noRecommendations: 'ذاتی نوعیت کی سفارشات حاصل کرنے کے لیے کچھ کورسز مکمل کریں!',

    lectures: 'اسباق',
    completed: 'مکمل',
    inProgress: 'جاری',
    notStarted: 'شروع نہیں ہوا',
    allLecturesDone: 'تمام اسباق مکمل! سرٹیفیکیٹ حاصل کرنے کے لیے کوئز دیں!',
    markComplete: 'مکمل نشان زد کریں',
    yourNotes: 'آپ کے نوٹس',
    saved: 'محفوظ',
    selectLecture: 'دیکھنے کے لیے کوئی سبق منتخب کریں',
    speed: 'رفتار',
    noVideo: 'کوئی YouTube ویڈیو دستیاب نہیں',
    addVideoUrl: 'براہ کرم ایڈمن پینل میں YouTube URL شامل کریں',
    courseLocked: 'کورس مقفل ہے',
    completeCurrentFirst: 'پہلے اپنا موجودہ کورس مکمل کریں۔',
    goToMyCourses: 'میرے کورسز پر جائیں',

    earnBadges: 'بیجز کمائیں، پوائنٹس جمع کریں، چیلنجز مکمل کریں، اور انعامات حاصل کریں!',
    yourBadges: 'آپ کے بیجز',
    noBadges: 'ابھی تک کوئی بیج نہیں۔ بیجز حاصل کرنے کے لیے سیکھنا شروع کریں!',
    pointsShop: 'پوائنٹس کی دکان',
    pointsAvailable: 'پوائنٹس دستیاب',
    noShopItems: 'دکان میں ابھی تک کوئی شے نہیں۔',
    todayChallenges: 'آج کے چیلنجز',
    allChallengesDone: 'آج کے تمام چیلنجز مکمل! کل دوبارہ آئیں۔',
    noChallenges: 'آج کے لیے کوئی چیلنج نہیں۔ کل دوبارہ چیک کریں!',
    earned: 'کمایا!',
    owned: 'اپنی ملکیت',
    buy: 'خریدیں',
    needMore: 'مزید چاہیے',
    claim: 'وصول کریں',
    claimed: 'وصول شدہ',
    locked: 'مقفل',

    upcomingClasses: 'آنے والی لائیو کلاسز',
    noUpcomingClasses: 'کوئی آنے والی لائیو کلاس نہیں',
    joinClass: 'کلاس میں شامل ہوں',
    classDetails: 'کلاس کی تفصیلات',
    instructor: 'انسٹرکٹر',
    platform: 'پلیٹ فارم',
    startTime: 'شروع ہونے کا وقت',
    endTime: 'ختم ہونے کا وقت',
    liveNow: 'لائیو',
    scheduled: 'مقررہ',
    ended: 'ختم شد',

    trackAssignments: 'اسائنمنٹس',
    noAssignments: 'اس ٹریک کے لیے کوئی اسائنمنٹ نہیں',
    submitAssignment: 'اسائنمنٹ جمع کروائیں',
    alreadySubmitted: 'پہلے ہی جمع کر دیا گیا',
    uploadFile: 'فائل اپ لوڈ کریں',
    textContent: 'متن',
    submit: 'جمع کروائیں',
    grade: 'گریڈ',
    feedback: 'رائے',
    dueDate: 'آخری تاریخ',
    totalPoints: 'کل پوائنٹس',
    assignmentSubmitted: 'اسائنمنٹ کامیابی سے جمع کر دی گئی!',

    pendingReviews: 'زیر التواء جائزے',
    noPendingReviews: 'کوئی زیر التواء جائزہ نہیں',
    clarity: 'واضحیت',
    completeness: 'مکمل ہونا',
    creativity: 'تخلیقی صلاحیت',
    comments: 'تبصرے',
    submitReview: 'جائزہ جمع کروائیں',
    reviewSubmitted: 'جائزہ کامیابی سے جمع ہو گیا!',
    myReviews: 'میرے جائزے',
    reviewsReceived: 'موصولہ جائزے',

    overview: 'جائزہ',
    password: 'پاس ورڈ',
    security: 'سیکیورٹی',
    activity: 'سرگرمی',
    emailVerification: 'ای میل تصدیق',
    verified: 'تصدیق شدہ',
    notVerified: 'تصدیق شدہ نہیں',
    resendEmail: 'دوبارہ بھیجیں',
    twoFactor: 'دو عوامل کی تصدیق',
    sessionManagement: 'سیشن کا انتظام',
    logoutAllDevices: 'تمام آلات سے لاگ آؤٹ',
    pushNotifications: 'پش نوٹیفیکیشنز',

    language: 'زبان',
    english: 'انگریزی',
    urdu: 'اردو',

    appearance: 'ظاہری شکل',
    theme: 'تھیم',
    accentColor: 'ایسنٹ رنگ',
    fontSize: 'فونٹ کا سائز',
    blue: 'نیلا',
    green: 'سبز',
    purple: 'جامنی',
    small: 'چھوٹا',
    medium: 'درمیانہ',
    large: 'بڑا',
    darkMode: 'ڈارک موڈ',
    lightMode: 'لائٹ موڈ',
  }
};

export const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
    document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
